### ISSUE TITLE
Integrity suite

### ISSUE THREAD

**Issue by benrudolph** [dimagi/loveseat#14]

**Comment by czue** [comment]
for some inspiration you could look at what I did for fixtures (though that was much more specific to the exact thing i wanted to do):

https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/cleanup/management/commands/couch_migrate.py#L50
https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/cleanup/management/commands/couch_migrations/fixtures.json#L9

**Comment by benrudolph** [comment]
thanks i'll take a look

**Comment by benrudolph** [comment]
ok so i thought about this over the weekend. i think it actually might be best to do this as a management command in hq for two reasons. one, it'll add a decent amount of complexity to the tool that wants to do profiling well. two, i don't think this is as useful as a feature. essentially we're testing couchdb's ability to replicate which they have dozens of tests for, so it's not something i think people would necessarily be looking for in the library. does that sound ok?

**Comment by czue** [comment]
for sure, that sounds fine...

**Comment by czue** [comment]
(will leave issue open until you have another place for it but feel free to close)

**Comment by benrudolph** [comment]
https://github.com/dimagi/commcare-hq/pull/6003
